IMG_SIZE = 64
N_INPUT_CHANNELS = 1
NUM_CLASSES=2
ALL_ARCHITECTURES = ['resnet20', 'resnet32', 'resnet44', 'resnet56']

# hybrid
EMBEDDING_DIM = [128, 256]
N_CONV_LAYERS_LIST=[1, 2, 3]
KERNEL_SIZE_LIST=[3, 5, 7]

POOLING_KERNEL_SIZE = 3
POOLING_STRIDE = 2
POOLING_PADDING = 1

NUM_LAYERS_LIST = [2, 4, 6, 7]
NUM_HEADS_LIST=[2, 4]


